FROM ubuntu:18.04

RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        wget git g++ make ca-certificates unzip \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/vlang

COPY . .

RUN make \
    && ln -s /opt/vlang/v /usr/local/bin/v \
    && mkdir -p /root/.vmodules/

CMD [ "bash" ]
